### ISSUE TITLE
JavaScript Errors

### ISSUE THREAD

**Issue by sebastian-marinescu** [Sterc/mediamanager#8]
Hi Sterc, 

I wanted to try out your media-manager, but after installing I get some errors in the console and uploading (or anything) is not working because of that. 

The initial errors: 
``` 
imageplus.min.js?v=v2.8.0:7 jQuery.Deferred exception: $(...).select2 is not a function TypeError: $(...).select2 is not a function
    at Object.setFilters (https://domain.tld/assets/components/mediamanager/js/mgr/mediamanager-files.js:373:39)
    at Object.init (https://domain.tld/assets/components/mediamanager/js/mgr/mediamanager-files.js:145:18)
    at HTMLDocument.<anonymous> (https://domain.tld/assets/components/mediamanager/js/mgr/mediamanager-files.js:1627:27)
    at e (https://domain.tld/assets/components/imageplus/js/mgr/imageplus.min.js?v=v2.8.0:7:49615)
    at t (https://domain.tld/assets/components/imageplus/js/mgr/imageplus.min.js?v=v2.8.0:7:49917) undefined
I.Deferred.exceptionHook @ imageplus.min.js?v=v2.8.0:7
imageplus.min.js?v=v2.8.0:7 Uncaught TypeError: $(...).select2 is not a function
    at Object.setFilters (mediamanager-files.js:373)
    at Object.init (mediamanager-files.js:145)
    at HTMLDocument.<anonymous> (mediamanager-files.js:1627)
    at e (imageplus.min.js?v=v2.8.0:7)
    at t (imageplus.min.js?v=v2.8.0:7)
```

After clicking on the "Upload" button, I get another one: 
```
mediamanager-files.js:280 Uncaught TypeError: $(...).slideToggle is not a function
    at Object.dropzoneOpen (mediamanager-files.js:280)
    at HTMLButtonElement.r (imageplus.min.js?v=v2.8.0:7)
    at HTMLDocument.dispatch (imageplus.min.js?v=v2.8.0:7)
    at HTMLDocument.m.handle (imageplus.min.js?v=v2.8.0:7)
```

**Comment by sebastian-marinescu** [comment]
Yesterday I came a little bit further, by adding these on `OnManagerPageInit`: 
``` 
            $modx->regClientCSS('/assets/website/css/select2.min.css');
            $modx->regClientCSS('/assets/website/css/jquery-ui.min.css');
            $modx->regClientCSS('/assets/website/css/jquery.modal.min.css');
            $modx->regClientStartupScript('/assets/website/js/select2.full.min.js');
            $modx->regClientStartupScript('/assets/website/js/jquery-ui.min.js');
            $modx->regClientStartupScript('/assets/website/js/jquery.modal.min.js');
``` 

But even then still `$.ajax` was missing, which I couldn't get to work (from the outside).

**Comment by sebastian-marinescu** [comment]
Tested the newest version and there were no JS-errors anymore 👍
